
name: demo_app
description: A combined Flutter app with Quiz and Weather features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_dotenv: ^5.1.0
  intl: any
  weather_icons: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
